CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE "meals_food" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "type" varchar(50) NOT NULL, "calories" integer NOT NULL, "protein" real NOT NULL, "carbs" real NOT NULL, "fats" real NOT NULL, "grams" real NOT NULL);
CREATE TABLE "meals_foodtag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tag_id" integer NOT NULL REFERENCES "meals_tag" ("id") DEFERRABLE INITIALLY DEFERRED, "food_id" bigint NOT NULL REFERENCES "meals_food" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_foodtag_tag_id_0ea74f72" ON "meals_foodtag" ("tag_id");
CREATE INDEX "meals_foodtag_food_id_845890e6" ON "meals_foodtag" ("food_id");
CREATE TABLE "meals_meal" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "grams" integer unsigned NOT NULL CHECK ("grams" >= 0), "link" varchar(200) NULL, "recipe" text NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "image" varchar(100) NULL, "popularity" integer NOT NULL);
CREATE INDEX "meals_meal_author_id_16816b88" ON "meals_meal" ("author_id");
CREATE TABLE "meals_mealproducts" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "grams" real NOT NULL, "food_id" bigint NOT NULL REFERENCES "meals_food" ("id") DEFERRABLE INITIALLY DEFERRED, "meal_id" bigint NOT NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_mealproducts_food_id_00b769a8" ON "meals_mealproducts" ("food_id");
CREATE INDEX "meals_mealproducts_meal_id_79c1fd6b" ON "meals_mealproducts" ("meal_id");
CREATE TABLE "meals_mealtag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tag_id" integer NOT NULL REFERENCES "meals_tag" ("id") DEFERRABLE INITIALLY DEFERRED, "meal_id" bigint NOT NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_mealtag_tag_id_ab539390" ON "meals_mealtag" ("tag_id");
CREATE INDEX "meals_mealtag_meal_id_4d720eb3" ON "meals_mealtag" ("meal_id");
CREATE TABLE "meals_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "type" varchar(50) NULL);
CREATE TABLE "meals_mealfavorites" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "meal_id" bigint NOT NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_mealfavorites_meal_id_86d358c5" ON "meals_mealfavorites" ("meal_id");
CREATE INDEX "meals_mealfavorites_user_id_dbdea8db" ON "meals_mealfavorites" ("user_id");
CREATE TABLE "meals_entry" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "grams" real NOT NULL, "meal_id" bigint NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED, "food_id" bigint NULL REFERENCES "meals_food" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_entry_user_id_870d0a7d" ON "meals_entry" ("user_id");
CREATE INDEX "meals_entry_meal_id_455960e6" ON "meals_entry" ("meal_id");
CREATE INDEX "meals_entry_food_id_7c3af2f1" ON "meals_entry" ("food_id");
CREATE TABLE "main_userdetails" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "age" smallint unsigned NOT NULL CHECK ("age" >= 0), "height_cm" smallint unsigned NOT NULL CHECK ("height_cm" >= 0), "weight_kg" real NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "activity_level" integer NOT NULL, "current_streak" integer unsigned NOT NULL CHECK ("current_streak" >= 0), "goal_calories" integer unsigned NOT NULL CHECK ("goal_calories" >= 0), "max_streak" integer unsigned NOT NULL CHECK ("max_streak" >= 0), "sex" varchar(10) NOT NULL, "calorie_plan" varchar(10) NOT NULL, "date_last_streak_entry" date NULL, "account_status" varchar(10) NOT NULL, "is_banned" bool NOT NULL, "role" varchar(10) NOT NULL);
CREATE TABLE "meals_mealcomment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "created_at" datetime NOT NULL, "meal_id" bigint NOT NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "meals_mealverification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "grams" integer unsigned NOT NULL CHECK ("grams" >= 0), "recipe" text NULL, "link" varchar(200) NULL, "image" varchar(100) NULL, "status" varchar(12) NOT NULL, "created_at" datetime NOT NULL, "reviewed_at" datetime NULL, "review_comment" text NULL, "author_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "original_meal_id" bigint NULL REFERENCES "meals_meal" ("id") DEFERRABLE INITIALLY DEFERRED, "reviewed_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "meals_mealverificationproduct" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "grams" real NOT NULL, "food_id" bigint NOT NULL REFERENCES "meals_food" ("id") DEFERRABLE INITIALLY DEFERRED, "verification_id" bigint NOT NULL REFERENCES "meals_mealverification" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "meals_mealverificationtag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tag_id" bigint NOT NULL REFERENCES "meals_tag" ("id") DEFERRABLE INITIALLY DEFERRED, "verification_id" bigint NOT NULL REFERENCES "meals_mealverification" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "meals_mealcomment_meal_id_70b9381e" ON "meals_mealcomment" ("meal_id");
CREATE INDEX "meals_mealcomment_user_id_735d4b37" ON "meals_mealcomment" ("user_id");
CREATE INDEX "meals_mealverification_author_id_e68e2070" ON "meals_mealverification" ("author_id");
CREATE INDEX "meals_mealverification_original_meal_id_8440b338" ON "meals_mealverification" ("original_meal_id");
CREATE INDEX "meals_mealverification_reviewed_by_id_4c616e9c" ON "meals_mealverification" ("reviewed_by_id");
CREATE INDEX "meals_mealverificationproduct_food_id_375eb9a9" ON "meals_mealverificationproduct" ("food_id");
CREATE INDEX "meals_mealverificationproduct_verification_id_e7a6b82b" ON "meals_mealverificationproduct" ("verification_id");
CREATE INDEX "meals_mealverificationtag_tag_id_0a042d60" ON "meals_mealverificationtag" ("tag_id");
CREATE INDEX "meals_mealverificationtag_verification_id_fbb3ff26" ON "meals_mealverificationtag" ("verification_id");
CREATE TABLE "user_managerrequest" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "full_name" varchar(120) NOT NULL, "phone" varchar(50) NOT NULL, "motivation" text NOT NULL, "resume" varchar(100) NULL, "status" varchar(12) NOT NULL, "admin_comment" text NULL, "created_at" datetime NOT NULL, "reviewed_at" datetime NULL, "reviewed_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "user_managerrequest_reviewed_by_id_1e429361" ON "user_managerrequest" ("reviewed_by_id");
CREATE INDEX "user_managerrequest_user_id_2ed716a4" ON "user_managerrequest" ("user_id");
