# Generated by Django 6.0 on 2026-01-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
