# Generated by Django 6.0 on 2026-01-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userdetails_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Sedentary'), (2, 'Lightly active'), (3, 'Moderately active'), (4, 'Very active'), (5, 'Extra active')], default=1),
            preserve_default=False,
        ),
    ]
