# Generated by Django 6.0 on 2026-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdetails_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='goal_calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='max_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
