# Generated by Django 6.0 on 2026-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userdetails_current_streak_userdetails_goal_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
