# Generated by Django 6.0 on 2026-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userdetails_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='calorie_plan',
            field=models.CharField(choices=[('cut', 'Похудання'), ('maintain', 'Статичний'), ('bulk', 'Набір ваги')], default='maintain', max_length=10),
        ),
    ]
