# Generated by Django 5.0 on 2026-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userdetails_calorie_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_last_streak_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
