# Generated by Django 6.0.3 on 2026-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='account_status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер'), ('admin', 'Адмін')], default='user', max_length=10),
        ),
    ]
