# Generated by Django 6.0 on 2026-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='grams',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='grams',
            field=models.FloatField(default=100),
        ),
    ]
