# Generated by Django 6.0 on 2026-01-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meal_food_mealproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='receipt',
            new_name='recipe',
        ),
    ]
