# Generated by Django 6.0 on 2026-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='grams',
            field=models.FloatField(default=100),
        ),
    ]
