# Generated by Django 6.0 on 2026-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_entry_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='grams',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
