# Generated by Django 6.0 on 2026-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_alter_meal_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
