# Generated by Django 6.0 on 2026-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='meals/meal_images/'),
        ),
    ]
