# Generated by Django 6.0 on 2026-01-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_tags_alter_foodtags_tag_alter_mealtags_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTags',
            new_name='FoodTag',
        ),
        migrations.RenameModel(
            old_name='MealTags',
            new_name='MealTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
