# Generated by Django 6.0 on 2026-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_rename_foodtags_foodtag_rename_mealtags_mealtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(through='meals.MealTag', to='meals.tag'),
        ),
    ]
