# Generated by Django 6.0 on 2026-01-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_meal_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='tags',
        ),
    ]
