# Generated by Django 6.0 on 2026-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0019_remove_meal_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
