# Generated by Django 6.0.3 on 2026-05-26 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('motivation', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='manager_resumes/')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('blocked', 'Заблоковано')], default='pending', max_length=12)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manager_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
